### ISSUE TITLE
[Android] Bottom visible bounds not respected in app

### ISSUE THREAD

**Issue by juliecantin** [nventive/ExtendedSplashScreen#80]
## Expected Behavior
When following the readme's instructions and adding the following line to the app, the app still takes into account the bottom notch on Android:

```
protected override void OnCreate(Bundle bundle)
{
	Nventive.ExtendedSplashScreen.ExtendedSplashScreen.AndroidSplashScreen = AndroidX.Core.SplashScreen.SplashScreen.InstallSplashScreen(this);
	base.OnCreate(bundle);
}
```

![image](https://github.com/nventive/ExtendedSplashScreen/assets/43351943/2e91054b-1818-4bd5-946e-4135e07326a6)

## Actual Behavior
When following the readme's instructions and adding the following line to the app, the app's content is partially hidden by the bottom notch on Android

```
protected override void OnCreate(Bundle bundle)
{
	Nventive.ExtendedSplashScreen.ExtendedSplashScreen.AndroidSplashScreen = AndroidX.Core.SplashScreen.SplashScreen.InstallSplashScreen(this);
	base.OnCreate(bundle);
}
```

![image](https://github.com/nventive/ExtendedSplashScreen/assets/43351943/0c1b8c96-0956-435d-a706-fdacb1754330)

https://github.com/nventive/ExtendedSplashScreen/assets/43351943/a7b0bad7-7f94-441a-b3cc-0329d936d18c

## Steps to Reproduce the Problem

1. Update the code of the sample in this repo with the following changes:
```
public class MainActivity : Microsoft.UI.Xaml.ApplicationActivity
{
	protected override void OnCreate(Bundle bundle)
	{
		Nventive.ExtendedSplashScreen.ExtendedSplashScreen.AndroidSplashScreen = AndroidX.Core.SplashScreen.SplashScreen.InstallSplashScreen(this);
		base.OnCreate(bundle);
	}
}
```

```
<Page x:Class="ExtendedSlashScreen.Uno.Samples.MainPage"
      xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
      xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
      xmlns:nventive="using:Nventive.ExtendedSplashScreen"
      xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
      xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
      mc:Ignorable="d">

	<TextBlock Text="Hello, world!"
			   FontSize="30"
			   VerticalAlignment="Bottom"
			   Foreground="Red"/>
</Page>
```
2. Launch the app on an Android device with the bottom notch (e.g. Pixel 6)

## Specifications

- Version: latest version of main
- Platform: Android
- Subsystem:

**Comment by jeanplevesque** [comment]
Can you explain the screenshot? I only see a black screen with some red lines at the bottom.
What is the expected result?
Can you post a video showing the transition from the native splash screen to the extended splash screen?

**Comment by juliecantin** [comment]
@jeanplevesque What happens is that the red text is largely hidden behind the notch

I've added a screenshot of what the main page looks like if we remove the call to the library, as well as a video of the app's launch.

**Comment by jeanplevesque** [comment]
Note that in order to keep a smooth transition between the native and extended splash screens, the app bars (top and bottom) appear on top of the extended splash screen and the app content.

The native splash screen takes the whole screen. The notch bars appear when we exit the native splash screen. For the transition to be smooth, the app doesn't resize. The notches are semi-transparent and are just overlaid on top of the app.

https://github.com/nventive/ExtendedSplashScreen/assets/39710855/4fc31d5e-f56e-4083-a234-a8f66980cd47

Also, your app has to account for safe area. In the previous video, we can see that the bottom notch overlaps the application. It means it would need code to account for the safe area in case content is at the bottom.
